"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.short_term_live_data import ShortTermLiveData


class TestShortTermLiveData(unittest.TestCase):
    """ShortTermLiveData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShortTermLiveData(self):
        """Test ShortTermLiveData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShortTermLiveData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
