"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.forecast_data_controller_api import ForecastDataControllerApi  # noqa: E501


class TestForecastDataControllerApi(unittest.TestCase):
    """ForecastDataControllerApi unit test stubs"""

    def setUp(self):
        self.api = ForecastDataControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_access_jupyter_notebook_using_post(self):
        """Test case for access_jupyter_notebook_using_post

        accessJupyterNotebook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
