"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.jupyter_call_back_api_controller_api import JupyterCallBackApiControllerApi  # noqa: E501


class TestJupyterCallBackApiControllerApi(unittest.TestCase):
    """JupyterCallBackApiControllerApi unit test stubs"""

    def setUp(self):
        self.api = JupyterCallBackApiControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jupyter_log_using_get(self):
        """Test case for jupyter_log_using_get

        jupyterLog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
