"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.short_term_live_data import ShortTermLiveData
globals()['ShortTermLiveData'] = ShortTermLiveData
from openapi_client.model.short_term_live_api_response_vo import ShortTermLiveApiResponseVO


class TestShortTermLiveApiResponseVO(unittest.TestCase):
    """ShortTermLiveApiResponseVO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShortTermLiveApiResponseVO(self):
        """Test ShortTermLiveApiResponseVO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShortTermLiveApiResponseVO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
