"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.livestock_list_data import LivestockListData


class TestLivestockListData(unittest.TestCase):
    """LivestockListData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLivestockListData(self):
        """Test LivestockListData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LivestockListData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
