"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.seamless_forecast_data import SeamlessForecastData


class TestSeamlessForecastData(unittest.TestCase):
    """SeamlessForecastData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSeamlessForecastData(self):
        """Test SeamlessForecastData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SeamlessForecastData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
