"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.nice_api_controller_api import NiceApiControllerApi  # noqa: E501


class TestNiceApiControllerApi(unittest.TestCase):
    """NiceApiControllerApi unit test stubs"""

    def setUp(self):
        self.api = NiceApiControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_nice_token_using_post(self):
        """Test case for get_nice_token_using_post

        getNiceToken  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
