"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.seamless_forecast_data import SeamlessForecastData
globals()['SeamlessForecastData'] = SeamlessForecastData
from openapi_client.model.seamless_forecast_api_response_vo import SeamlessForecastApiResponseVO


class TestSeamlessForecastApiResponseVO(unittest.TestCase):
    """SeamlessForecastApiResponseVO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSeamlessForecastApiResponseVO(self):
        """Test SeamlessForecastApiResponseVO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SeamlessForecastApiResponseVO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
