"""
    Api Documentation

    Api Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError



class LivestockListData(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'breeding_method': (str,),  # noqa: E501
            'breeding_scale': (int,),  # noqa: E501
            'cooling_pad_size': (int,),  # noqa: E501
            'fan_size': (int,),  # noqa: E501
            'insulation_type': (str,),  # noqa: E501
            'latitude': (float,),  # noqa: E501
            'length': (str,),  # noqa: E501
            'livestock_kinds': (str,),  # noqa: E501
            'livestock_name': (str,),  # noqa: E501
            'livestock_width': (float,),  # noqa: E501
            'longitude': (float,),  # noqa: E501
            'number_of_fan': (int,),  # noqa: E501
            'raising_days': (date,),  # noqa: E501
            'ridge_height': (float,),  # noqa: E501
            'road_address': (str,),  # noqa: E501
            'roof_insulation_thickness': (int,),  # noqa: E501
            'roof_urethane_option': (bool,),  # noqa: E501
            'side_height': (float,),  # noqa: E501
            'use_cooling_pad': (bool,),  # noqa: E501
            'wall_insulation_thickness': (int,),  # noqa: E501
            'wall_urethane_option': (bool,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'breeding_method': 'breedingMethod',  # noqa: E501
        'breeding_scale': 'breedingScale',  # noqa: E501
        'cooling_pad_size': 'coolingPadSize',  # noqa: E501
        'fan_size': 'fanSize',  # noqa: E501
        'insulation_type': 'insulationType',  # noqa: E501
        'latitude': 'latitude',  # noqa: E501
        'length': 'length',  # noqa: E501
        'livestock_kinds': 'livestockKinds',  # noqa: E501
        'livestock_name': 'livestockName',  # noqa: E501
        'livestock_width': 'livestockWidth',  # noqa: E501
        'longitude': 'longitude',  # noqa: E501
        'number_of_fan': 'numberOfFan',  # noqa: E501
        'raising_days': 'raisingDays',  # noqa: E501
        'ridge_height': 'ridgeHeight',  # noqa: E501
        'road_address': 'roadAddress',  # noqa: E501
        'roof_insulation_thickness': 'roofInsulationThickness',  # noqa: E501
        'roof_urethane_option': 'roofUrethaneOption',  # noqa: E501
        'side_height': 'sideHeight',  # noqa: E501
        'use_cooling_pad': 'useCoolingPad',  # noqa: E501
        'wall_insulation_thickness': 'wallInsulationThickness',  # noqa: E501
        'wall_urethane_option': 'wallUrethaneOption',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """LivestockListData - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            breeding_method (str): 사육방식. [optional]  # noqa: E501
            breeding_scale (int): 개체수. [optional]  # noqa: E501
            cooling_pad_size (int): 쿨링패드사이즈. [optional]  # noqa: E501
            fan_size (int): 팬사이즈. [optional]  # noqa: E501
            insulation_type (str): 단열재종류. [optional]  # noqa: E501
            latitude (float): 위도. [optional]  # noqa: E501
            length (str): 길이. [optional]  # noqa: E501
            livestock_kinds (str): 축종. [optional]  # noqa: E501
            livestock_name (str): 축사이름. [optional]  # noqa: E501
            livestock_width (float): 폭. [optional]  # noqa: E501
            longitude (float): 경도. [optional]  # noqa: E501
            number_of_fan (int): 팬개수. [optional]  # noqa: E501
            raising_days (date): 입식일. [optional]  # noqa: E501
            ridge_height (float): 동고. [optional]  # noqa: E501
            road_address (str): 주소. [optional]  # noqa: E501
            roof_insulation_thickness (int): 지붕단열재두께. [optional]  # noqa: E501
            roof_urethane_option (bool): 지붕우레탄옵션. [optional]  # noqa: E501
            side_height (float): 축고. [optional]  # noqa: E501
            use_cooling_pad (bool): 쿨링패드사용유무. [optional]  # noqa: E501
            wall_insulation_thickness (int): 벽면단열재두께. [optional]  # noqa: E501
            wall_urethane_option (bool): 벽면우레탄옵션. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """LivestockListData - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            breeding_method (str): 사육방식. [optional]  # noqa: E501
            breeding_scale (int): 개체수. [optional]  # noqa: E501
            cooling_pad_size (int): 쿨링패드사이즈. [optional]  # noqa: E501
            fan_size (int): 팬사이즈. [optional]  # noqa: E501
            insulation_type (str): 단열재종류. [optional]  # noqa: E501
            latitude (float): 위도. [optional]  # noqa: E501
            length (str): 길이. [optional]  # noqa: E501
            livestock_kinds (str): 축종. [optional]  # noqa: E501
            livestock_name (str): 축사이름. [optional]  # noqa: E501
            livestock_width (float): 폭. [optional]  # noqa: E501
            longitude (float): 경도. [optional]  # noqa: E501
            number_of_fan (int): 팬개수. [optional]  # noqa: E501
            raising_days (date): 입식일. [optional]  # noqa: E501
            ridge_height (float): 동고. [optional]  # noqa: E501
            road_address (str): 주소. [optional]  # noqa: E501
            roof_insulation_thickness (int): 지붕단열재두께. [optional]  # noqa: E501
            roof_urethane_option (bool): 지붕우레탄옵션. [optional]  # noqa: E501
            side_height (float): 축고. [optional]  # noqa: E501
            use_cooling_pad (bool): 쿨링패드사용유무. [optional]  # noqa: E501
            wall_insulation_thickness (int): 벽면단열재두께. [optional]  # noqa: E501
            wall_urethane_option (bool): 벽면우레탄옵션. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
